version: '3.8'

services:
  web:
    image: devops-app:latest
    ports:
      - "80:80"
    restart: always
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
