name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Build imagen web
        run: docker build -t devops-app:latest .

      - name: Build imagen API
        run: docker build -t devops-api:latest ./api

      - name: Exportar imágenes
        run: |
          docker save devops-app:latest | gzip > devops-app.tar.gz
          docker save devops-api:latest | gzip > devops-api.tar.gz

      - name: Copiar imágenes a EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "devops-app.tar.gz,devops-api.tar.gz,docker-compose.yml"
          target: "~/"

      - name: Deploy en EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker load < ~/devops-app.tar.gz
            docker load < ~/devops-api.tar.gz

            docker stop web-app 2>/dev/null || true
            docker rm web-app 2>/dev/null || true

            docker stack deploy -c ~/docker-compose.yml devops-stack
            docker service update --force devops-stack_web
            docker service update --force devops-stack_api

            echo "✅ Deploy exitoso"